### ISSUE TITLE
Btrfs subvolume layout - flat vs nested.

### ISSUE THREAD

**Issue by chewblacka** [Guekka/nixos-server#2]
I'm opening an issue because it's easier than a fork (I've already forked your code). Just want to say thanks for the repo! I've been playing with this for the last couple of weeks. Just one tip. If you set a top-level btfrs subvolume, e.g. "@" in your nix-setup script, then you can have a flat btrfs subvolume structure  and don't need to delete any subvolumes of root at boot - you just delete `root `directly and replace with it's copy `root-blank`. 
So `nix-setup.sh` would look like:

```
mount "$DISK"3 /mnt
btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@/root
btrfs subvolume create /mnt/@/home
btrfs subvolume create /mnt/@/nix
btrfs subvolume create /mnt/@/persist
btrfs subvolume create /mnt/@/log
```
I realized this after I was trying to get [disko](https://github.com/nix-community/disko) working with impermanence, and I  couldn't get it to work properly with nested subvolumes (though I may have just been doing something wrong!). There is  a good discussion on the [old btrfs wiki](https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/index.php/SysadminGuide.html#Layout) on flat vs nested subvolumes They each have their pros and cons. I think I find flat easier to work with.

Anyway thanks again!

**Comment by chewblacka** [comment]
**EDIT:** Just realized I also had to create `/tmp` and `/srv` as subdirectories of the initial `root` subvolume just after creation (before snapshotting it to `root-blank`). I think system-d creates those two directories as subvolumes in the initial mount when we want to erase `root` and replace with a new copy of `root-blank` so that seems to create issues if not already present. 

For good measure I also have subvolumes for `/var/lib/machines` and `/var/lib/portables` because potentially (at least) I won't those volumes to persist.

**Comment by Guekka** [comment]
I really appreciate the feedback, and I'm glad I helped you. Honestly, I didn't expect anyone to read this article
I'm gonna have a try with you way. If I find your way better, I'll update the article (and credit you of course)

Thanks for mentioning disko, too. It does look very interesting

**Comment by Guekka** [comment]
I made the move to disko a few months ago. I kept the nested layout, as it worked fine for me. You can check it [here](https://github.com/Guekka/nixos-server/blob/3-sharing/hosts/common/optional/impermanence-disko.nix)
