### ISSUE TITLE
State not being reset on reboot

### ISSUE THREAD

**Issue by Another-Andrew** [Guekka/nixos-server#4]
Hi, I found your guide [here](https://guekka.github.io/nixos-server-1/) and it is exactly what I'm looking for. First, I'd like to thank you for your great write up on the general concepts and how to implement them. I'd like to host some services within a QEMU virtual machine running NixOS 23.05 on my server. Because of this, I did not have to change almost any of your configuration settings. I only had to change the size of my **swap** and **root** partitions. Other than that, I followed your guide to the t. I'm stuck at the section labeled **Configuring impermanence** Upon reboot two errors stick out to me. Here's the output of my boot log. 

```
<<< NixOS Stage 1 >>>

loading module virtio_balloon...
loading module virtio_console...
loading module virtio_rng...
loading module btrfs...
loading module dm_mod...
running udev...
Starting systemd-udevd version 253.6
Starting device mapper and LVM...
Scanning for Btrfs filesystems
registered: /dev/vda3
mounting /dev/disk/by-uuid/da2b0efd-50ca-4542-a4de-03dc106f8f2c on /...
mounting /dev/disk/by-uuid/da2b0efd-50ca-4542-a4de-03dc106f8f2c on /persist...
mounting /dev/disk/by-uuid/da2b0efd-50ca-4542-a4de-03dc106f8f2c on /nix...
mounting /dev/disk/by-uuid/da2b0efd-50ca-4542-a4de-03dc106f8f2c on /var/log...

<<< NixOS Stage 2 >>>

running activation script...
setting up /etc...
A file already exists at /etc/machine-id
A file already exists at /etc/ssh/ssh_host_ed25519_key!
A file already exists at /etc/ssh/ssh_host_ed25519_key.pub!
A file already exists at /etc/ssh/ssh_host_rsa_key!
A file already exists at /etc/ssh/ssh_host_rsa_key.pub!
Activation script snippet 'persist-files' failed (1)
starting systemd...

Welcome to NixOS 23.05 (Stoat)!
```

A little further into boot: 

```
[  OK  ] Mounted HugePages File System.
[  OK  ] Mounted POSIX Message Queue File System.
[  OK  ] Mounted Kernel Debug File System.
[  OK  ] Finished Create List of Static Device Nodes.
[  OK  ] Finished Load Kernel Module configs.
[  OK  ] Finished Load Kernel Module fuse.
[  OK  ] Finished Load Kernel Module drm.
[  OK  ] Started Journal Service.
[FAILED] Failed to start Bind mount or link '/etc/machine-id' to '/etc/machine-id'.
See 'systemctl status persist--persist-etc-machine-id-.service' for details.
[FAILED] Failed to start Bind mount or link 'key' to '/etc/ssh/ssh_host_ed25519_key'.
See 'systemctl status persist--persist-etc-ssh-ssh_host_ed25519_key-.service' for details.
[FAILED] Failed to start Bind mount or link 'h' to '/etc/ssh/ssh_host_ed25519_key.pub'.
See 'systemctl status persist--persist-etc-ssh-ssh_host_ed25519_key.pub-.service' for details.
[FAILED] Failed to start Bind mount or link 'rsa_key' to '/etc/ssh/ssh_host_rsa_key'.
See 'systemctl status persist--persist-etc-ssh-ssh_host_rsa_key-.service' for details.
[FAILED] Failed to start Bind mount or link 'pub' to '/etc/ssh/ssh_host_rsa_key.pub'.
See 'systemctl status persist--persist-etc-ssh-ssh_host_rsa_key.pub-.service' for details.
[  OK  ] Finished Coldplug All udev Devices.
[  OK  ] Finished Remount Root and Kernel File Systems.
[  OK  ] Finished Load Kernel Modules.
```

Any files that I add to the root directory do not get wiped by the snapshot taken from a clean state. Any help would be greatly appreciated. Please let me know if I can provide any more information. 

Thank you!

**Comment by Guekka** [comment]
Sorry for the late answer, I completely missed that issue @ChapelCone 

Thanks for reading the article :)

Since it's been several months, did you find a solution, or do you still need help?

**Comment by NireBryce** [comment]
if you did find a quick fix I'd love to know, otherwise I'll try to remember this exists when I figure it out.

edit: nevermind, my issue is https://discourse.nixos.org/t/impermanence-a-file-already-exists-at-etc-machine-id/20267/6
> Ignore the error, it’s a warning. Your machine-id file will be regenerated on boot and be placed into the persistent location since a symlink will point to it. If you want it to happen ahead of time then simply rm /etc/machine-id and then activate the system configuration. The same thing happens with home-manager if you try to write your .basrhc with it, but you already have a .bashrc in your home directory. Similarly, in that case, you need to rm ~/.bashrc before home-manager can take over. Home-manager has an option to force the replacement of the file, which I enjoy. Impermanence has no such ‘force’ option, but I think it would be a good idea to add.

**Comment by Guekka** [comment]
I'm closing this issue, since the OP did not answer. Feel free to open another one 😃
